-- AlterEnum: add Faculty, Maintenance Supervisor, and Event Organizer roles
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FACULTY' AFTER 'STUDENT';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MAINTENANCE_SUPERVISOR' AFTER 'MAINTENANCE_STAFF';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'EVENT_ORGANIZER' AFTER 'MAINTENANCE_SUPERVISOR';

-- AlterEnum: add Assigned and Waiting ticket statuses (MNT-4, MNT-6)
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED' AFTER 'OPEN';
ALTER TYPE "TicketStatus" ADD VALUE IF NOT EXISTS 'WAITING' AFTER 'IN_PROGRESS';
